<navigation-bar :user="{{ auth()->user()->toJson() }}"
    :tenant="{{ $isTenantDashboard ? $tenant->toJson() : 'null' }}"
    :is-tenant-dashboard="{{ $isTenantDashboard ? 'true' : 'false' }}"
    :is-impersonating="{{ auth()->user()->isImpersonating() ? 'true' : 'false' }}"
    :is-admin="{{ auth()->user()->isAdmin() ? 'true' : 'false' }}"
    :is-impersonatable="{{ auth()->user()-> isImpersonatable() ? 'true' : 'false' }}"
    :is-impersonator="{{ auth()->user()->isImpersonator() ? 'true' : 'false' }}"
    :is-impersonated="{{ auth()->user()->isImpersonated() ? 'true' : 'false' }}"
    :is-impersonation-enabled="{{ auth()->user()->isImpersonationEnabled() ? 'true' : 'false' }}"
    :is-impersonation-disabled="{{ auth()->user()->isImpersonationDisabled() ? 'true' : 'false' }}"
    :is-impersonation-allowed="{{ auth()->user()->isImpersonationAllowed() ? 'true' : 'false' }}"
    :is-impersonation-not-allowed="{{ auth()->user()->isImpersonationNotAllowed() ? 'true' : 'false' }}"
    :is-impersonation-possible="{{ auth()->user()->isImpersonationPossible() ? 'true' : 'false' }}"
    :is-impersonation-not-possible="{{ auth()->user()->isImpersonationNotPossible() ? 'true' : 'false' }}"
    :is-impersonation-active="{{ auth()->user()->isImpersonationActive() ? 'true' : 'false' }}"
    :is-impersonation-inactive="{{ auth()->user()->isImpersonationInactive() ? 'true' : 'false' }}"
    :is-impersonation-current="{{ auth()->user()->isImpersonationCurrent() ? 'true' : 'false' }}"
    :is-impersonation-not-current="{{ auth()->user()->isImpersonationNotCurrent() ? 'true' : 'false' }}"
    :is-impersonation-initiated="{{ auth()->user()->isImpersonationInitiated() ? 'true' : 'false' }}"
    :is-impersonation-not-initiated="{{ auth()->user()->isImpersonationNotInitiated() ? 'true' : 'false' }}"
    :is-impersonation-terminated="{{ auth()->user()->isImpersonationTerminated() ? 'true' : 'false' }}"
    :is-impersonation-not-terminated="{{ auth()->user()->isImpersonationNotTerminated() ? 'true' : 'false' }}"
    :is-impersonation-allowed="{{ auth()->user()->isImpersonationAllowed() ? 'true' : 'false' }}"
    :is-impersonation-not-allowed="{{ auth()->user()->isImpersonationNotAllowed() ? 'true' : 'false' }}"
></navigation-bar>
<element-theme-selctor></element-theme-selctor>